In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

from matplotlib import cm

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import MiniBatchKMeans

%matplotlib inline

In [2]:
df = pd.read_pickle('BMTC.pickle')

In [4]:
df.head()

LATITUDE1  LONGITUDE1  LATITUDE2  LONGITUDE2  LATITUDE3  LONGITUDE3  \
0  12.845321   77.667030  12.845290   77.666107  12.845347   77.665565   
1  12.965988   77.535179  12.965984   77.535217  12.965984   77.535217   
2  12.957028   77.559196  12.956954   77.559349  12.956981   77.559494   
3  13.020818   77.502739  13.020818   77.502739  13.020818   77.502739   
4  12.982555   77.603226  12.982555   77.603226  12.982555   77.603226   

   LATITUDE4  LONGITUDE4  LATITUDE5  LONGITUDE5  ...    LONGITUDE96  \
0  12.845364   77.664871  12.845376   77.664261  ...      77.625946   
1  12.965984   77.535217  12.965984   77.535217  ...      77.535217   
2  12.957012   77.559494  12.957021   77.559479  ...      77.549812   
3  13.020818   77.502739  13.020818   77.502739  ...      77.502739   
4  12.982556   77.603226  12.982556   77.603226  ...      77.598190   

   LATITUDE97  LONGITUDE97  LATITUDE98  LONGITUDE98  LATITUDE99  LONGITUDE99  \
0   12.912030    77.625778   12.912779    77.625366   12.913666    77.624832   
1   12.965984    77.535217   12.965984    77.535217   12.965984    77.535217   
2   12.925502    77.549606   12.925762    77.549080   12.926178    77.548477   
3   13.020818    77.502739   13.020818    77.502739   13.020818    77.502739   
4   12.983925    77.597755   12.983923    77.597389   12.983922    77.597397   

   LATITUDE100  LONGITUDE100   Time  
0    12.914212     77.624512  23550  
1    12.965984     77.535217  19353  
2    12.926508     77.548103  19574  
3    13.020818     77.502739   9692  
4    12.983919     77.597389  68284  

[5 rows x 201 columns]

In [3]:
df1 = pd.read_csv('test.csv')

In [4]:
test = pd.DataFrame()

In [7]:
df1.head()

Id            TimeStamp                      LATLONG1  \
0  150220445  2016-07-22 06:32:30   12.845321:77.66703000000003   
1  150811705  2016-07-31 05:22:33  12.965988000000001:77.535179   
2  150218073  2016-07-22 05:26:14           12.957028:77.559196   
3  150218420  2016-07-23 02:41:32  13.020817999999998:77.502739   
4  150219092  2016-07-22 18:58:04           12.982555:77.603226   

                       LATLONG2                      LATLONG3  \
0  12.845289999999999:77.666107           12.845347:77.665565   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2           12.956954:77.559349  12.956980999999999:77.559494   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4           12.982555:77.603226           12.982555:77.603226   

                       LATLONG4                              LATLONG5  \
0   12.845364:77.66487099999998                   12.845376:77.664261   
1  12.965983999999999:77.535217          12.965983999999999:77.535217   
2  12.957011999999999:77.559494  12.957021000000001:77.55947900000002   
3  13.020817999999998:77.502739          13.020817999999998:77.502739   
4           12.982556:77.603226                   12.982556:77.603226   

                       LATLONG6                      LATLONG7  \
0            12.84543:77.663361  12.845457000000001:77.662323   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2   12.957024:77.55947900000002   12.957024:77.55947900000002   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4           12.982556:77.603226           12.982556:77.603226   

                       LATLONG8              ...               \
0           12.845512:77.661636              ...                
1  12.965983999999999:77.535217              ...                
2    12.95702:77.55947900000002              ...                
3  13.020817999999998:77.502739              ...                
4           12.982556:77.603226              ...                

                      LATLONG91                     LATLONG92  \
0  12.907288000000001:77.628647           12.908197:77.628113   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2  12.927736999999999:77.551399           12.927241:77.551102   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4            12.98435:77.600571           12.984285:77.600075   

                      LATLONG93                     LATLONG94  \
0           12.909328:77.627449    12.910283999999999:77.6269   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2           12.926368:77.550606           12.925618:77.550125   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4           12.984244:77.599525            12.984176:77.59906   

                      LATLONG95                     LATLONG96  \
0           12.911159:77.626396           12.911705:77.625946   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2   12.925413:77.55001800000002           12.925419:77.549812   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4           12.984106:77.598648             12.98403:77.59819   

                      LATLONG97                     LATLONG98  \
0            12.91203:77.625778  12.912778999999999:77.625366   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2   12.925502:77.54960600000003   12.925761999999999:77.54908   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4           12.983925:77.597755  12.983922999999999:77.597389   

                      LATLONG99                    LATLONG100  
0  12.913666000000001:77.624832           12.914212:77.624512  
1  12.965983999999999:77.535217  12.965983999999999:77.535217  
2           12.926178:77.548477           12.926508:77.548103  
3  13.020817999999998:77.502739  13.020817999999998:77.502739  
4           12.983922:77.597397           12.983919:77.597389  

[5 rows x 102 columns]

In [5]:
train = pd.read_pickle('train15.pickle')

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 415016 entries, 3 to 487464
Data columns (total 16 columns):
ID                    415016 non-null object
Start_Time            415016 non-null datetime64[ns]
End_Time              415016 non-null datetime64[ns]
Start_Latitude        415016 non-null float64
Start_Longitude       415016 non-null float64
End_Latitude          415016 non-null float64
End_Longitude         415016 non-null float64
Duration              415016 non-null float64
pickup_date           415016 non-null object
pickup_weekday        415016 non-null int64
pickup_hour           415016 non-null int64
pickup_month          415016 non-null int64
pickup_day            415016 non-null int64
haversine_distance    415016 non-null float64
pickup_cluster        415016 non-null int32
dropoff_cluster       415016 non-null int32
dtypes: datetime64[ns](2), float64(6), int32(2), int64(4), object(2)
memory usage: 50.7+ MB


In [6]:
test['ID'] = df1['Id']

In [7]:
test['Start_Time'] = pd.to_datetime(df1['TimeStamp'])

In [8]:
test['Start_Latitude'] = df['LATITUDE1']

In [9]:
test['Start_Latitude'] = df['LATITUDE1']

In [10]:
test['End_Latitude'] = df['LATITUDE2']
test['End_Longitude'] = df['LONGITUDE2']

In [21]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 6 columns):
ID                 108 non-null int64
Start_Time         108 non-null datetime64[ns]
Start_Latitude     108 non-null float64
Start_Longitude    108 non-null float64
End_Latitude       108 non-null float64
End_Longitude      108 non-null float64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 5.1 KB


In [11]:
def kmeanret(test):
    coords = np.vstack((test[['Start_Latitude',  'Start_Longitude']].values,
                        test[['End_Latitude', 'End_Longitude']].values,
                        test[['Start_Latitude',  'Start_Longitude']].values,
                        test[['End_Latitude', 'End_Longitude']].values))
    kmeans = MiniBatchKMeans(n_clusters=100, batch_size=10000).fit(coords)
    return kmeans

In [14]:
from haversine import haversine
def derive_features(df):
    df = df.copy()
    # Pickup-based features
    df['pickup_date'] = df['Start_Time'].dt.date
    df['pickup_weekday'] = df['Start_Time'].dt.weekday
    df['pickup_hour'] = df['Start_Time'].dt.hour
    df['pickup_month'] = df['Start_Time'].dt.month
    df['pickup_day'] = df['Start_Time'].dt.day
    # Brand new features
    df['haversine_distance'] = df.apply(lambda x: haversine((x['Start_Latitude'],  x['Start_Longitude']), 
                                                            (x['End_Latitude'], x['End_Longitude'])), axis=1)
    df['pickup_cluster']  = kmeans.predict(df[['Start_Latitude', 'Start_Longitude']])
    df['dropoff_cluster'] = kmeans.predict(df[['End_Latitude', 'End_Longitude']])
    return df

In [15]:
test = derive_features(test)

In [16]:
test.head()

ID          Start_Time  Start_Latitude  Start_Longitude  \
0  150220445 2016-07-22 06:32:30       12.845321        77.667030   
1  150811705 2016-07-31 05:22:33       12.965988        77.535179   
2  150218073 2016-07-22 05:26:14       12.957028        77.559196   
3  150218420 2016-07-23 02:41:32       13.020818        77.502739   
4  150219092 2016-07-22 18:58:04       12.982555        77.603226   

   End_Latitude  End_Longitude pickup_date  pickup_weekday  pickup_hour  \
0     12.914212      77.624512  2016-07-22               4            6   
1     12.965984      77.535217  2016-07-31               6            5   
2     12.926508      77.548103  2016-07-22               4            5   
3     13.020818      77.502739  2016-07-23               5            2   
4     12.983919      77.597389  2016-07-22               4           18   

   pickup_month  pickup_day  haversine_distance  pickup_cluster  \
0             7          22            8.939923              94   
1             7          31            0.004142              68   
2             7          22            3.600305              98   
3             7          23            0.000000              23   
4             7          22            0.650385              29   

   dropoff_cluster  
0               64  
1               68  
2               90  
3               23  
4               29

In [17]:
d = ['ID','Start_Time','pickup_date']

In [18]:
test.drop(d,axis=1,inplace=True)

In [19]:
test.head()

Start_Latitude  Start_Longitude  End_Latitude  End_Longitude  \
0       12.845321        77.667030     12.914212      77.624512   
1       12.965988        77.535179     12.965984      77.535217   
2       12.957028        77.559196     12.926508      77.548103   
3       13.020818        77.502739     13.020818      77.502739   
4       12.982555        77.603226     12.983919      77.597389   

   pickup_weekday  pickup_hour  pickup_month  pickup_day  haversine_distance  \
0               4            6             7          22            8.939923   
1               6            5             7          31            0.004142   
2               4            5             7          22            3.600305   
3               5            2             7          23            0.000000   
4               4           18             7          22            0.650385   

   pickup_cluster  dropoff_cluster  
0              94               64  
1              68               68  
2              98               90  
3              23               23  
4              29               29

In [20]:
dvalid = xgb.DMatrix(test)

In [36]:
dvalid

In [21]:
import pickle

In [22]:
loaded_model = pickle.load(open('model1.sav', 'rb'))

In [23]:
ytest = loaded_model.predict(dvalid)

In [24]:
ytest

array([7.2956777, 4.180949 , 6.5447106, 5.3106456, 6.5239778, 6.5676756,
       7.540527 , 4.9594   , 6.266545 , 6.0242662, 5.166883 , 5.927511 ,
       7.317218 , 5.8023777, 6.922781 , 6.779944 , 6.1938305, 6.870197 ,
       6.1427717, 6.6797743, 6.866709 , 6.453557 , 5.270932 , 4.7349687,
       7.172161 , 5.018754 , 5.3799386, 6.4438524, 7.3774514, 6.9080997,
       6.929503 , 5.2644   , 5.65974  , 6.751001 , 7.1693535, 6.3798847,
       6.585369 , 6.643067 , 6.7797885, 6.2540584, 5.8983197, 7.341718 ,
       6.867265 , 7.080347 , 6.749561 , 6.58357  , 6.3955493, 4.6735215,
       7.3865924, 6.6467915, 6.0816474, 7.5973005, 6.110114 , 6.7787704,
       7.1631756, 7.2060466, 7.09236  , 6.6619906, 6.597782 , 7.44357  ,
       5.479862 , 5.5436635, 6.149863 , 6.4575295, 5.546368 , 5.2374067,
       6.741817 , 7.0064754, 7.251569 , 6.5457697, 6.703865 , 4.537017 ,
       4.843788 , 6.667633 , 7.417703 , 7.5823364, 7.523161 , 7.449968 ,
       4.937013 , 6.2933383, 6.864053 , 6.152752 , 

In [25]:
t2 = np.expm1(ytest)

In [26]:
t2 = t2.astype(int)

In [27]:
t2

array([1472,   64,  694,  201,  680,  710, 1881,  141,  525,  412,  174,
        374, 1505,  330, 1014,  879,  488,  962,  464,  795,  958,  633,
        193,  112, 1301,  150,  216,  627, 1598,  999, 1020,  192,  286,
        853, 1298,  588,  723,  766,  878,  519,  363, 1542,  959, 1187,
        852,  722,  598,  106, 1613,  769,  436, 1991,  449,  877, 1290,
       1346, 1201,  781,  732, 1707,  238,  254,  467,  636,  255,  187,
        846, 1102, 1409,  695,  814,   92,  125,  785, 1664, 1962, 1849,
       1718,  138,  539,  956,  469,  943, 1339,  840,  426, 1227, 1695,
       1597, 1036,  296,  187,  386,  903, 1317,  409,  944,  195, 1227,
        263,  449, 1704,  460,  431, 1230, 1215,  386,  326])

In [71]:
m = t2/60

In [51]:
s = t2%60

In [72]:
m = m.astype(int)
m

array([ 4,  1,  2,  4,  3, 13, 11,  3,  7,  6,  4,  6,  3,  4,  5,  7,  8,
        3,  6,  4,  2,  7,  4,  1,  7,  2,  2,  3,  4,  1,  5,  5,  5, 11,
        1,  9,  7, 13,  8,  9,  4,  4,  9,  4,  7,  5,  4,  2,  6,  6,  6,
        4,  3,  7,  6,  7,  6,  4,  6,  6,  3,  2,  8, 18,  1,  1,  3,  3,
       11,  3,  3,  2,  2,  2, 14,  9, 10,  3,  2,  2, 11,  6,  2, 21,  6,
        2,  2,  2,  6, 10,  3,  3,  4,  9,  6,  3,  8,  2,  3,  5,  8,  3,
        8,  5,  7,  1,  3,  3])

In [55]:
s

array([32, 52,  4,  1, 27, 33, 34, 36, 14, 26, 45,  5, 12, 35, 57, 37, 59,
       41, 10, 35, 50, 17,  6, 52, 15, 37, 50, 42, 29, 47, 33, 36, 41, 39,
        7, 59, 25, 46, 14, 57, 43, 41, 39, 17, 17, 12, 16,  4, 14, 58,  6,
       30, 28,  5, 14, 15,  0, 16, 54,  0, 24, 28, 52, 12, 58, 36, 40, 52,
       55, 48, 47, 28, 24, 59, 14, 49, 35, 29, 35, 50,  0, 21,  8,  1, 35,
       14, 56, 48, 39, 16, 55, 53, 47,  9,  9, 23,  0, 58,  6, 47, 39, 10,
       20,  1, 10, 24, 47, 51])

In [57]:
h = m/60

In [60]:
h = h.astype(int)
h

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
v = pd.to_datetime(df1['TimeStamp'])+(pd.to_timedelta(s, unit='s'))
v = v+(pd.to_timedelta(m, unit='m'))
v = v+(pd.to_timedelta(h, unit='h'))

In [77]:
v.head()

0   2016-07-22 06:37:02
1   2016-07-31 05:24:25
2   2016-07-22 05:28:18
3   2016-07-23 02:45:33
4   2016-07-22 19:01:31
dtype: datetime64[ns]

In [75]:
df1['TimeStamp'].head()

0    2016-07-22 06:32:30
1    2016-07-31 05:22:33
2    2016-07-22 05:26:14
3    2016-07-23 02:41:32
4    2016-07-22 18:58:04
Name: TimeStamp, dtype: object

In [85]:
res = np.zeros(108)
res

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [87]:
for i in range(1,100):
    time = pd.Series()
    if i == 1:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(df1['TimeStamp'])
        test['Start_Latitude'] = df['LATITUDE1']
        test['Start_Longitude'] = df['LONGITUDE1']
        test['End_Latitude'] = df['LATITUDE2']
        test['End_Longitude'] = df['LONGITUDE2']
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))
    else:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(time)
        test['Start_Latitude'] = df['LATITUDE{}'.format(i)]
        test['Start_Longitude'] = df['LONGITUDE{}'.format(i)]
        test['End_Latitude'] = df['LATITUDE{}'.format(i+1)]
        test['End_Longitude'] = df['LONGITUDE{}'.format(i+1)]
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))

In [88]:
res

array([27358., 12250., 33064., 27380., 17883., 49210., 15622., 27186.,
       35798., 51478., 25116., 38146., 19946., 30087., 21990., 32216.,
       33767., 30341., 16643., 15938., 20260., 29244., 34398., 10781.,
       21374., 26757., 16486., 27596., 20589., 33105., 18525., 33576.,
       29548., 21810., 24189., 37885., 47169., 29953., 44291., 58911.,
       29255., 30083., 48509., 29139., 26120., 22269., 25941., 14966.,
       27219., 20365., 14748., 21304., 26839., 19874., 20669., 31903.,
       20857., 31399., 27945., 19481., 14850., 19181., 35864., 36012.,
       14238., 12837., 21931., 19719., 36259., 30680., 23397., 27104.,
       24398., 19453., 37705., 23084., 21808., 19915., 23410., 15444.,
       38165., 34154., 26927., 39109., 18221., 15652., 25696., 20286.,
       23494., 21170., 41445., 31186., 33664., 18296., 22057., 31091.,
       38097., 23390., 21938., 14415., 21417., 19934., 19622., 15053.,
       19813., 29348., 31894., 35213.])

In [94]:
res = res.astype(int)

In [90]:
sub_df = pd.DataFrame()

In [92]:
sam_sub = pd.read_csv('sample_submission.csv')

In [93]:
sam_sub.head()

Id  Duration
0  150220445         0
1  150811705         0
2  150218073         0
3  150218420         0
4  150219092         0

In [97]:
sub_df['Id'] = df1['Id']
sub_df['Duration'] = res

In [101]:
sub_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 2 columns):
Id          108 non-null int64
Duration    108 non-null int64
dtypes: int64(2)
memory usage: 1.8 KB


In [104]:
sub_df.to_csv('FirstSubmission.csv',index=False)

In [105]:
sub_df1 = pd.read_csv('FirstSubmission.csv')

In [106]:
sub_df1.head()

Id  Duration
0  150220445     27358
1  150811705     12250
2  150218073     33064
3  150218420     27380
4  150219092     17883