In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

from matplotlib import cm

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import MiniBatchKMeans

%matplotlib inline

In [2]:
df = pd.read_pickle('BMTC.pickle')

In [3]:
df.head()

LATITUDE1  LONGITUDE1  LATITUDE2  LONGITUDE2  LATITUDE3  LONGITUDE3  \
0  12.845321   77.667030  12.845290   77.666107  12.845347   77.665565   
1  12.965988   77.535179  12.965984   77.535217  12.965984   77.535217   
2  12.957028   77.559196  12.956954   77.559349  12.956981   77.559494   
3  13.020818   77.502739  13.020818   77.502739  13.020818   77.502739   
4  12.982555   77.603226  12.982555   77.603226  12.982555   77.603226   

   LATITUDE4  LONGITUDE4  LATITUDE5  LONGITUDE5  ...    LONGITUDE96  \
0  12.845364   77.664871  12.845376   77.664261  ...      77.625946   
1  12.965984   77.535217  12.965984   77.535217  ...      77.535217   
2  12.957012   77.559494  12.957021   77.559479  ...      77.549812   
3  13.020818   77.502739  13.020818   77.502739  ...      77.502739   
4  12.982556   77.603226  12.982556   77.603226  ...      77.598190   

   LATITUDE97  LONGITUDE97  LATITUDE98  LONGITUDE98  LATITUDE99  LONGITUDE99  \
0   12.912030    77.625778   12.912779    77.625366   12.913666    77.624832   
1   12.965984    77.535217   12.965984    77.535217   12.965984    77.535217   
2   12.925502    77.549606   12.925762    77.549080   12.926178    77.548477   
3   13.020818    77.502739   13.020818    77.502739   13.020818    77.502739   
4   12.983925    77.597755   12.983923    77.597389   12.983922    77.597397   

   LATITUDE100  LONGITUDE100   Time  
0    12.914212     77.624512  23550  
1    12.965984     77.535217  19353  
2    12.926508     77.548103  19574  
3    13.020818     77.502739   9692  
4    12.983919     77.597389  68284  

[5 rows x 201 columns]

In [4]:
df1 = pd.read_csv('test.csv')

In [5]:
test = pd.DataFrame()

In [6]:
df1.head()

Id            TimeStamp                      LATLONG1  \
0  150220445  2016-07-22 06:32:30   12.845321:77.66703000000003   
1  150811705  2016-07-31 05:22:33  12.965988000000001:77.535179   
2  150218073  2016-07-22 05:26:14           12.957028:77.559196   
3  150218420  2016-07-23 02:41:32  13.020817999999998:77.502739   
4  150219092  2016-07-22 18:58:04           12.982555:77.603226   

                       LATLONG2                      LATLONG3  \
0  12.845289999999999:77.666107           12.845347:77.665565   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2           12.956954:77.559349  12.956980999999999:77.559494   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4           12.982555:77.603226           12.982555:77.603226   

                       LATLONG4                              LATLONG5  \
0   12.845364:77.66487099999998                   12.845376:77.664261   
1  12.965983999999999:77.535217          12.965983999999999:77.535217   
2  12.957011999999999:77.559494  12.957021000000001:77.55947900000002   
3  13.020817999999998:77.502739          13.020817999999998:77.502739   
4           12.982556:77.603226                   12.982556:77.603226   

                       LATLONG6                      LATLONG7  \
0            12.84543:77.663361  12.845457000000001:77.662323   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2   12.957024:77.55947900000002   12.957024:77.55947900000002   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4           12.982556:77.603226           12.982556:77.603226   

                       LATLONG8              ...               \
0           12.845512:77.661636              ...                
1  12.965983999999999:77.535217              ...                
2    12.95702:77.55947900000002              ...                
3  13.020817999999998:77.502739              ...                
4           12.982556:77.603226              ...                

                      LATLONG91                     LATLONG92  \
0  12.907288000000001:77.628647           12.908197:77.628113   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2  12.927736999999999:77.551399           12.927241:77.551102   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4            12.98435:77.600571           12.984285:77.600075   

                      LATLONG93                     LATLONG94  \
0           12.909328:77.627449    12.910283999999999:77.6269   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2           12.926368:77.550606           12.925618:77.550125   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4           12.984244:77.599525            12.984176:77.59906   

                      LATLONG95                     LATLONG96  \
0           12.911159:77.626396           12.911705:77.625946   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2   12.925413:77.55001800000002           12.925419:77.549812   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4           12.984106:77.598648             12.98403:77.59819   

                      LATLONG97                     LATLONG98  \
0            12.91203:77.625778  12.912778999999999:77.625366   
1  12.965983999999999:77.535217  12.965983999999999:77.535217   
2   12.925502:77.54960600000003   12.925761999999999:77.54908   
3  13.020817999999998:77.502739  13.020817999999998:77.502739   
4           12.983925:77.597755  12.983922999999999:77.597389   

                      LATLONG99                    LATLONG100  
0  12.913666000000001:77.624832           12.914212:77.624512  
1  12.965983999999999:77.535217  12.965983999999999:77.535217  
2           12.926178:77.548477           12.926508:77.548103  
3  13.020817999999998:77.502739  13.020817999999998:77.502739  
4           12.983922:77.597397           12.983919:77.597389  

[5 rows x 102 columns]

In [7]:
train = pd.read_pickle('train15.pickle')

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 415016 entries, 3 to 487464
Data columns (total 16 columns):
ID                    415016 non-null object
Start_Time            415016 non-null datetime64[ns]
End_Time              415016 non-null datetime64[ns]
Start_Latitude        415016 non-null float64
Start_Longitude       415016 non-null float64
End_Latitude          415016 non-null float64
End_Longitude         415016 non-null float64
Duration              415016 non-null float64
pickup_date           415016 non-null object
pickup_weekday        415016 non-null int64
pickup_hour           415016 non-null int64
pickup_month          415016 non-null int64
pickup_day            415016 non-null int64
haversine_distance    415016 non-null float64
pickup_cluster        415016 non-null int32
dropoff_cluster       415016 non-null int32
dtypes: datetime64[ns](2), float64(6), int32(2), int64(4), object(2)
memory usage: 50.7+ MB


In [9]:
test['ID'] = df1['Id']

In [10]:
test['Start_Time'] = pd.to_datetime(df1['TimeStamp'])

In [11]:
test['Start_Latitude'] = df['LATITUDE1']
test['Start_Longitude'] = df['LONGITUDE1']
test['End_Latitude'] = df['LATITUDE100']
test['End_Longitude'] = df['LONGITUDE100']

In [12]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 6 columns):
ID                 108 non-null int64
Start_Time         108 non-null datetime64[ns]
Start_Latitude     108 non-null float64
Start_Longitude    108 non-null float64
End_Latitude       108 non-null float64
End_Longitude      108 non-null float64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 5.1 KB


In [13]:
def kmeanret(test):
    coords = np.vstack((test[['Start_Latitude',  'Start_Longitude']].values,
                        test[['End_Latitude', 'End_Longitude']].values,
                        test[['Start_Latitude',  'Start_Longitude']].values,
                        test[['End_Latitude', 'End_Longitude']].values))
    kmeans = MiniBatchKMeans(n_clusters=100, batch_size=10000).fit(coords)
    return kmeans

In [14]:
coords = np.vstack((test[['Start_Latitude',  'Start_Longitude']].values,
                        test[['End_Latitude', 'End_Longitude']].values,
                        test[['Start_Latitude',  'Start_Longitude']].values,
                        test[['End_Latitude', 'End_Longitude']].values))
kmeans = MiniBatchKMeans(n_clusters=100, batch_size=10000).fit(coords)

In [15]:
from haversine import haversine
def derive_features(df):
    df = df.copy()
    # Pickup-based features
    df['pickup_date'] = df['Start_Time'].dt.date
    df['pickup_weekday'] = df['Start_Time'].dt.weekday
    df['pickup_hour'] = df['Start_Time'].dt.hour
    df['pickup_month'] = df['Start_Time'].dt.month
    df['pickup_day'] = df['Start_Time'].dt.day
    # Brand new features
    df['haversine_distance'] = df.apply(lambda x: haversine((x['Start_Latitude'],  x['Start_Longitude']), 
                                                            (x['End_Latitude'], x['End_Longitude'])), axis=1)
    df['pickup_cluster']  = kmeans.predict(df[['Start_Latitude', 'Start_Longitude']])
    df['dropoff_cluster'] = kmeans.predict(df[['End_Latitude', 'End_Longitude']])
    return df

In [16]:
test = derive_features(test)

In [17]:
test.head()

ID          Start_Time  Start_Latitude  Start_Longitude  \
0  150220445 2016-07-22 06:32:30       12.845321        77.667030   
1  150811705 2016-07-31 05:22:33       12.965988        77.535179   
2  150218073 2016-07-22 05:26:14       12.957028        77.559196   
3  150218420 2016-07-23 02:41:32       13.020818        77.502739   
4  150219092 2016-07-22 18:58:04       12.982555        77.603226   

   End_Latitude  End_Longitude pickup_date  pickup_weekday  pickup_hour  \
0     12.914212      77.624512  2016-07-22               4            6   
1     12.965984      77.535217  2016-07-31               6            5   
2     12.926508      77.548103  2016-07-22               4            5   
3     13.020818      77.502739  2016-07-23               5            2   
4     12.983919      77.597389  2016-07-22               4           18   

   pickup_month  pickup_day  haversine_distance  pickup_cluster  \
0             7          22            8.939923               6   
1             7          31            0.004142              47   
2             7          22            3.600305              83   
3             7          23            0.000000              27   
4             7          22            0.650385              21   

   dropoff_cluster  
0               12  
1               47  
2               92  
3               27  
4               21

In [18]:
d = ['ID','Start_Time','pickup_date']

In [19]:
test.drop(d,axis=1,inplace=True)

In [20]:
test.head()

Start_Latitude  Start_Longitude  End_Latitude  End_Longitude  \
0       12.845321        77.667030     12.914212      77.624512   
1       12.965988        77.535179     12.965984      77.535217   
2       12.957028        77.559196     12.926508      77.548103   
3       13.020818        77.502739     13.020818      77.502739   
4       12.982555        77.603226     12.983919      77.597389   

   pickup_weekday  pickup_hour  pickup_month  pickup_day  haversine_distance  \
0               4            6             7          22            8.939923   
1               6            5             7          31            0.004142   
2               4            5             7          22            3.600305   
3               5            2             7          23            0.000000   
4               4           18             7          22            0.650385   

   pickup_cluster  dropoff_cluster  
0               6               12  
1              47               47  
2              83               92  
3              27               27  
4              21               21

In [21]:
dvalid = xgb.DMatrix(test)

In [22]:
import pickle
loaded_model = pickle.load(open('model1.sav', 'rb'))

In [23]:
ytest = loaded_model.predict(dvalid)

In [24]:
ytest

array([7.1871734, 4.638264 , 6.6965327, 5.2611413, 6.7019167, 6.3244495,
       7.7335277, 5.3262787, 6.0511174, 6.4797826, 5.8195543, 6.483231 ,
       7.4728622, 4.9389486, 6.971393 , 6.959101 , 6.2136626, 6.228837 ,
       6.2276506, 6.927259 , 6.6943455, 6.133131 , 5.4979224, 4.8306074,
       7.567481 , 5.0015874, 5.6038866, 6.596625 , 6.9057717, 6.8506975,
       6.9951277, 5.695751 , 6.085622 , 6.274256 , 7.0848494, 5.9571176,
       6.439977 , 6.6419134, 6.7755785, 6.2869124, 5.5935917, 6.8350067,
       6.6028028, 7.0780234, 7.104189 , 6.9742084, 6.1066704, 5.6290355,
       7.7117863, 7.000804 , 6.389185 , 7.5258427, 6.179718 , 6.4980874,
       7.3648515, 7.6195984, 6.786861 , 6.3644967, 7.013349 , 6.989098 ,
       5.280736 , 5.5436635, 6.581779 , 6.3886704, 5.658598 , 5.2601056,
       6.6980963, 7.169082 , 7.031593 , 6.4259276, 6.8091097, 4.908089 ,
       6.035093 , 7.078112 , 7.566613 , 7.3852744, 7.5189652, 7.2764745,
       5.7372227, 6.0608215, 7.2478147, 6.196198 , 

In [25]:
t2 = np.expm1(ytest)

In [26]:
t2 = t2.astype(int)

In [27]:
t2

array([1321,  102,  808,  191,  812,  557, 2282,  204,  423,  650,  335,
        653, 1758,  138, 1064, 1051,  498,  506,  505, 1018,  806,  459,
        243,  124, 1933,  147,  270,  731,  997,  943, 1090,  296,  438,
        529, 1192,  385,  625,  765,  875,  536,  267,  928,  736, 1184,
       1216, 1067,  447,  277, 2233, 1096,  594, 1854,  481,  662, 1578,
       2036,  885,  579, 1110, 1083,  195,  254,  720,  594,  285,  191,
        809, 1297, 1130,  616,  905,  134,  416, 1184, 1931, 1611, 1841,
       1444,  309,  427, 1404,  489, 1235, 1103, 1187,  368, 1157, 1268,
       1755, 1463,  321,  167,  392,  950, 1046,  366,  963,  142, 2176,
        286,  263, 1213,  421,  431,  842, 1367,  294,  335])

In [28]:
res = np.zeros(108)

In [30]:
for i in range(1,100):
    time = pd.Series()
    if i == 1:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(df1['TimeStamp'])
        test['Start_Latitude'] = df['LATITUDE1']
        test['Start_Longitude'] = df['LONGITUDE1']
        test['End_Latitude'] = df['LATITUDE2']
        test['End_Longitude'] = df['LONGITUDE2']
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))
        i = i+19
    else:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(time)
        test['Start_Latitude'] = df['LATITUDE{}'.format(i)]
        test['Start_Longitude'] = df['LONGITUDE{}'.format(i)]
        test['End_Latitude'] = df['LATITUDE{}'.format(i+1)]
        test['End_Longitude'] = df['LONGITUDE{}'.format(i+1)]
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))
        i = i+20

In [38]:
res

array([26639., 12326., 33456., 30262., 18753., 46330., 14995., 25620.,
       36154., 52333., 25571., 39614., 18958., 29339., 20482., 31494.,
       32316., 29752., 15519., 16684., 19765., 29787., 32080., 10205.,
       21779., 27968., 16320., 27077., 19961., 30794., 17925., 33688.,
       29915., 21239., 23709., 40535., 48034., 28722., 44067., 60653.,
       29734., 30775., 47128., 30108., 24934., 21731., 26407., 14718.,
       25410., 19789., 14055., 19718., 27439., 19454., 20891., 29654.,
       20507., 31897., 27213., 18790., 15056., 18843., 36811., 37691.,
       13858., 12689., 20215., 19400., 35635., 27498., 23067., 25013.,
       24237., 19661., 34419., 21655., 21565., 20259., 23752., 15498.,
       39664., 34656., 25346., 38457., 18042., 16731., 25844., 21000.,
       23343., 19950., 40462., 28001., 36366., 17642., 21972., 28846.,
       36305., 22939., 20988., 14316., 21158., 19182., 19853., 14652.,
       18752., 29308., 31074., 35282.])

In [32]:
sub_df = pd.DataFrame()
sub_df['Id'] = df1['Id']
sub_df['Duration'] = t2
sub_df.to_csv('FirstSubmission1.csv',index=False)

In [35]:
sub = pd.read_csv('FirstSubmission1.csv')

In [36]:
sub.head()

Id  Duration
0  150220445      1052
1  150811705        70
2  150218073       642
3  150218420       206
4  150219092       611

In [43]:
res = np.zeros(108)

In [44]:
for i in range(1,3):
    time = pd.Series()
    if i == 1:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(df1['TimeStamp'])
        test['Start_Latitude'] = df['LATITUDE1']
        test['Start_Longitude'] = df['LONGITUDE1']
        test['End_Latitude'] = df['LATITUDE50']
        test['End_Longitude'] = df['LONGITUDE50']
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))
        i = i+49
    else:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(time)
        test['Start_Latitude'] = df['LATITUDE{}'.format(i)]
        test['Start_Longitude'] = df['LONGITUDE{}'.format(i)]
        test['End_Latitude'] = df['LATITUDE{}'.format(i+50)]
        test['End_Longitude'] = df['LONGITUDE{}'.format(i+50)]
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))

In [45]:
res

array([1732.,  229., 1076.,  348., 1137., 1642., 1426.,  557.,  954.,
       1469.,  647.,  752.,  671.,  410., 1822.,  796.,  926.,  754.,
        782., 1270.,  468.,  764.,  514.,  197., 1834.,  422.,  385.,
       1266., 1191., 1423., 1424.,  773.,  528.,  947., 1217., 1715.,
       1512.,  842., 1393., 1477.,  781.,  524., 1621.,  597., 1632.,
       1110.,  654.,  396., 1385.,  692.,  662., 1676.,  349., 1263.,
       1053., 1098., 1197.,  757., 1634., 1353.,  349.,  393., 1076.,
       1273.,  539.,  372., 1141.,  712., 1469., 1097., 1633.,  335.,
        716.,  907., 1910., 1143., 1410., 1364.,  513.,  412., 1975.,
        823., 1122., 1630.,  665.,  236., 1523., 1562., 1002., 1249.,
        782.,  367., 1174.,  711., 1314.,  879.,  853.,  529., 1257.,
        446.,  796.,  994.,  702.,  645., 1690., 1452.,  785.,  869.])

In [33]:
sub_df = pd.DataFrame()
sub_df['Id'] = df1['Id']
sub_df['Duration'] = res
sub_df.to_csv('FirstSubmission2.csv',index=False)

In [46]:
res = res = np.zeros(108)

In [47]:
l = [1,20,40,60,80]
for i in l:
    time = pd.Series()
    if i == 1:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(df1['TimeStamp'])
        test['Start_Latitude'] = df['LATITUDE1']
        test['Start_Longitude'] = df['LONGITUDE1']
        test['End_Latitude'] = df['LATITUDE20']
        test['End_Longitude'] = df['LONGITUDE20']
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))
    else:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(time)
        test['Start_Latitude'] = df['LATITUDE{}'.format(i)]
        test['Start_Longitude'] = df['LONGITUDE{}'.format(i)]
        test['End_Latitude'] = df['LATITUDE{}'.format(i+20)]
        test['End_Longitude'] = df['LONGITUDE{}'.format(i+20)]
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))

In [48]:
res

array([1828.,  560., 1395.,  983., 1499., 2190., 1356., 1358., 1984.,
       2879., 1489., 1905., 1231., 1422., 1459., 1552., 2028., 1314.,
       1149., 1160., 1393., 1942., 1273.,  457., 1534., 1138.,  777.,
       1898., 1845., 1338., 1295., 1612., 1579., 1402., 1801., 1719.,
       2178., 1127., 2157., 3012., 1438., 1056., 2932., 1847., 1856.,
       1535., 1588.,  741., 2453., 1418.,  912., 1794., 1450., 1482.,
       1740., 2496., 1582., 1852., 1525., 1523.,  808.,  977., 1818.,
       1721.,  661.,  655., 1428., 1673., 1723., 1766., 1783.,  774.,
       1264., 1740., 1380., 1167., 1244., 1693., 1066.,  772., 2868.,
       1223., 1578., 1275., 1343.,  736., 1742., 1819., 1435., 1693.,
       1824., 1156., 1458., 1300., 1737., 1388., 2057., 1095., 1580.,
        930., 1949., 1173., 1514.,  791., 1192., 1500., 1434., 2218.])

In [49]:
sub_df = pd.DataFrame()
sub_df['Id'] = df1['Id']
sub_df['Duration'] = res
sub_df.to_csv('FirstSubmission3.csv',index=False)

In [50]:
res = res = np.zeros(108)

In [54]:
l = [1,10,20,30,40,50,60,70,80,90]
for i in l:
    time = pd.Series()
    if i == 1:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(df1['TimeStamp'])
        test['Start_Latitude'] = df['LATITUDE1']
        test['Start_Longitude'] = df['LONGITUDE1']
        test['End_Latitude'] = df['LATITUDE10']
        test['End_Longitude'] = df['LONGITUDE10']
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))
    else:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(time)
        test['Start_Latitude'] = df['LATITUDE{}'.format(i)]
        test['Start_Longitude'] = df['LONGITUDE{}'.format(i)]
        test['End_Latitude'] = df['LATITUDE{}'.format(i+10)]
        test['End_Longitude'] = df['LONGITUDE{}'.format(i+10)]
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))

In [55]:
res

array([ 4682.,  2509.,  5102.,  4311.,  4603.,  9050.,  3858.,  4691.,
        8663., 10888.,  5591.,  8193.,  4999.,  6257.,  4684.,  6269.,
        6776.,  5725.,  3761.,  3505.,  4025.,  6269.,  5418.,  1879.,
        5119.,  5642.,  3503.,  6993.,  5413.,  3569.,  3173.,  6068.,
        5878.,  4772.,  4345.,  8109.,  7729.,  5068.,  8734., 12518.,
        6101.,  5232., 10927.,  6817.,  6103.,  4262.,  5958.,  3222.,
        4963.,  3952.,  3324.,  4816.,  5132.,  3810.,  4402.,  7752.,
        4301.,  8188.,  4751.,  4131.,  3142.,  4104.,  7856.,  6192.,
        2564.,  2825.,  4298.,  4385.,  6092.,  5494.,  4403.,  3728.,
        5802.,  4719.,  4379.,  6054.,  4844.,  3783.,  4903.,  3508.,
        9294.,  5237.,  5383.,  5333.,  4061.,  3153.,  4056.,  4883.,
        4284.,  4856.,  7663.,  5053.,  5657.,  4524.,  4271.,  4381.,
        5335.,  4887.,  4433.,  3530.,  5525.,  5107.,  4656.,  2801.,
        3929.,  5470.,  5313.,  7978.])

In [56]:
sub_df = pd.DataFrame()
sub_df['Id'] = df1['Id']
sub_df['Duration'] = res
sub_df.to_csv('FirstSubmission5.csv',index=False)

In [60]:
res = res = np.zeros(108)

In [66]:
l = list(range(1,100,3))
print(l)

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]


In [67]:

for i in l:
    time = pd.Series()
    if i == 1:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(df1['TimeStamp'])
        test['Start_Latitude'] = df['LATITUDE1']
        test['Start_Longitude'] = df['LONGITUDE1']
        test['End_Latitude'] = df['LATITUDE4']
        test['End_Longitude'] = df['LONGITUDE4']
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))
    else:
        test = pd.DataFrame()
        test['ID'] = df1['Id']
        test['Start_Time'] = pd.to_datetime(time)
        test['Start_Latitude'] = df['LATITUDE{}'.format(i)]
        test['Start_Longitude'] = df['LONGITUDE{}'.format(i)]
        test['End_Latitude'] = df['LATITUDE{}'.format(i+3)]
        test['End_Longitude'] = df['LONGITUDE{}'.format(i+3)]
        kmeans = kmeanret(test)
        test = derive_features(test)
        time = test['Start_Time']
        d = ['ID','Start_Time','pickup_date']
        test.drop(d,axis=1,inplace=True)
        dvalid = xgb.DMatrix(test)
        ytest = loaded_model.predict(dvalid)
        ydur = np.expm1(ytest)
        ydur = ydur.astype(int)
        s = ydur%60
        m = ydur/60
        m = m.astype(int)
        h = m/60
        h = h.astype(int)
        res = res + ydur
        time = time + (pd.to_timedelta(s, unit='s'))
        time = time + (pd.to_timedelta(m, unit='m'))
        time = time + (pd.to_timedelta(h, unit='h'))

In [68]:
res

array([ 6218.,  4181.,  7283., 10649.,  5869., 15222.,  5545.,  8497.,
       13479., 17975.,  8278., 12643.,  6897.,  9685.,  6899.,  9600.,
       10981.,  8989.,  5585.,  5440.,  6940., 10809., 10570.,  3240.,
        8004.,  9563.,  5507.,  9407.,  7477.,  8483.,  6297.,  9417.,
        9352.,  7497.,  7487., 13184., 16501.,  8709., 14578., 19698.,
        9573.,  9125., 16003., 10907.,  9230.,  6873.,  8786.,  5252.,
        7680.,  7481.,  4774.,  6984.,  9731.,  5907.,  7353.,  9966.,
        7866., 11361.,  9149.,  6074.,  5200.,  6168., 11901., 11453.,
        4173.,  4501.,  6331.,  6413., 10404.,  8596.,  7749.,  5908.,
        9657.,  6827.,  9445.,  6921.,  7142.,  6346.,  8178.,  5988.,
       12033., 10568.,  7846.,  9608.,  5429.,  5487.,  9279.,  6331.,
        7921.,  7165., 13167.,  8969.,  9458.,  7098.,  6825.,  8762.,
       11265.,  7763.,  7205.,  5035.,  7476.,  6418.,  6606.,  4778.,
        6212.,  9284.,  9283., 11910.])

In [69]:
sub_df = pd.DataFrame()
sub_df['Id'] = df1['Id']
sub_df['Duration'] = res
sub_df.to_csv('FirstSubmission6.csv',index=False)